import type { Case, Evidence, Fact, TimelineEvent, Conflict, MissingInformation, CaseStatus } from "../../types/case";
import type { ResolutionRecommendation, RecommendationStatus } from "../../types/resolution";
import type { ActionPackage, ActionPackageStatus, CommunicationDraft } from "../../types/action-package";
export interface CaseRepository { create(input:Pick<Case,"userId"|"title"|"category"|"description"|"priority"|"situation"|"people">):Promise<Case>; getById(id:string,userId:string):Promise<Case|undefined>; listByUser(userId:string):Promise<Case[]>; update(id:string,userId:string,patch:Partial<Pick<Case,"title"|"description"|"status"|"priority"|"situation">>):Promise<Case|undefined>; }
export interface EvidenceRepository { create(evidence:Evidence):Promise<Evidence>; getById(id:string):Promise<Evidence|undefined>; getByCaseId(caseId:string):Promise<Evidence[]>; updateProcessingStatus(id:string,status:Evidence["processingStatus"],patch?:Partial<Evidence>):Promise<Evidence|undefined>; }
export interface FactRepository { createMany(facts:Fact[]):Promise<Fact[]>; getByCaseId(caseId:string):Promise<Fact[]>; replaceForEvidence(caseId:string,sourceId:string,facts:Fact[]):Promise<Fact[]>; }
export interface TimelineRepository { replaceForCase(caseId:string,events:TimelineEvent[]):Promise<TimelineEvent[]>; getByCaseId(caseId:string):Promise<TimelineEvent[]>; }
export interface ConflictRepository { replaceForCase(caseId:string,conflicts:Conflict[]):Promise<Conflict[]>; getByCaseId(caseId:string):Promise<Conflict[]>; }
export interface MissingInformationRepository { replaceForCase(caseId:string,items:MissingInformation[]):Promise<MissingInformation[]>; getByCaseId(caseId:string):Promise<MissingInformation[]>; }
export interface RecommendationRepository { create(recommendation:ResolutionRecommendation):Promise<ResolutionRecommendation>; getLatestByCaseId(caseId:string):Promise<ResolutionRecommendation|undefined>; listByCaseId(caseId:string):Promise<ResolutionRecommendation[]>; updateStatus(id:string,status:RecommendationStatus):Promise<ResolutionRecommendation|undefined>; }
export interface ActionPackageRepository { create(actionPackage:ActionPackage):Promise<ActionPackage>; getById(id:string):Promise<ActionPackage|undefined>; getLatestByCaseId(caseId:string):Promise<ActionPackage|undefined>; listByCaseId(caseId:string):Promise<ActionPackage[]>; updateStatus(id:string,status:ActionPackageStatus):Promise<ActionPackage|undefined>; updateCommunication(id:string,communication:CommunicationDraft):Promise<ActionPackage|undefined>; }
export interface Repositories { cases:CaseRepository; evidence:EvidenceRepository; facts:FactRepository; timeline:TimelineRepository; conflicts:ConflictRepository; missing:MissingInformationRepository; recommendations:RecommendationRepository; actionPackages:ActionPackageRepository; getAggregate(id:string,userId:string):Promise<Case|undefined>; setStatus(id:string,userId:string,status:CaseStatus):Promise<Case|undefined>; }
