import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { getRepositories } from "@/lib/db";
import { getStorageProvider } from "@/lib/storage";
import { validateUpload } from "@/lib/evidence/validation";
import { processEvidence } from "@/lib/evidence/pipeline";
import type { Evidence } from "@/types/case";
const DEMO_USER_ID="user-demo";
export async function GET(_:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const record=await getRepositories().getAggregate(id,DEMO_USER_ID);if(!record)return NextResponse.json({error:"We couldn't find that case."},{status:404});return NextResponse.json({evidence:record.evidence});}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const {id}=await params;const repositories=getRepositories();const record=await repositories.getAggregate(id,DEMO_USER_ID);if(!record)return NextResponse.json({error:"We couldn't find that case."},{status:404});try{const form=await request.formData();const value=form.get("file");if(!value||typeof value==="string")return NextResponse.json({error:"Choose a file before uploading."},{status:400});const blob=value as Blob&{name?:string;type?:string};const bytes=new Uint8Array(await blob.arrayBuffer());const validated=validateUpload({filename:blob.name,mimeType:blob.type,size:bytes.byteLength,data:bytes});const storageKey=`${id}/${randomUUID()}-${validated.filename}`;const stored=await getStorageProvider().upload({storageKey,data:validated.data,contentType:validated.mimeType});const now=new Date().toISOString();const evidence:Evidence={id:`evidence-${randomUUID()}`,caseId:id,filename:validated.filename,mimeType:validated.mimeType,size:validated.size,storageKey:stored.storageKey,storageUrl:stored.url,sourceType:"upload",processingStatus:"pending",extractedFactsCount:0,uploadedAt:now,createdAt:now,updatedAt:now,sizeLabel:`${Math.max(1,Math.round(validated.size/1024))} KB`};await repositories.evidence.create(evidence);const result=await processEvidence(evidence.id,DEMO_USER_ID);return NextResponse.json({case:result.caseData,evidence:result.evidence});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"We couldn't store that file."},{status:400});}}
