import { describe, expect, it } from "vitest";
import { createCaseSchema } from "../lib/validation/case";
import { validateUpload } from "../lib/evidence/validation";
import { extractFactsFromText } from "../lib/facts/rule-based";
import { validateExtractedFact } from "../lib/facts/validation";
import { detectConflicts } from "../lib/facts/conflicts";
import { findMissingInformation } from "../lib/facts/missing";
import { buildTimeline } from "../lib/timeline/builder";
import type { Fact } from "../types/case";

describe("case intake boundary",()=>{it("rejects empty or too-short descriptions",()=>{expect(createCaseSchema.safeParse({description:""}).success).toBe(false);expect(createCaseSchema.safeParse({description:"It broke"}).success).toBe(false);});it("accepts a useful problem description",()=>{expect(createCaseSchema.safeParse({description:"My phone arrived damaged and the seller has not refunded me."}).success).toBe(true);});});
describe("file validation",()=>{const data=new Uint8Array([1,2,3]);it("accepts supported text",()=>{expect(validateUpload({filename:"notes.txt",mimeType:"text/plain",size:data.byteLength,data}).extension).toBe(".txt");});it("rejects unsupported and oversized files",()=>{expect(()=>validateUpload({filename:"notes.exe",mimeType:"application/octet-stream",size:3,data})).toThrow("isn't supported");expect(()=>validateUpload({filename:"notes.txt",mimeType:"text/plain",size:3*1024*1024,data})).toThrow("smaller than");});});
describe("fact extraction and provenance",()=>{it("extracts deterministic text facts",()=>{const candidates=extractFactsFromText("ExampleMart order RX-1024\nAmount: ₹18,499\nDelivered Aug 07.");expect(candidates.some(fact=>fact.factType==="order_id")).toBe(true);expect(candidates.some(fact=>fact.factType==="delivery_date"&&fact.normalizedValue==="2026-08-07")).toBe(true);});it("rejects malformed confidence and dates",()=>{expect(()=>validateExtractedFact({factType:"date",value:"tomorrow",confidence:1.1,extractionMethod:"parser"},{caseId:"case-1",sourceId:"evidence-1"})).toThrow();});});
function fact(id:string,type:Fact["factType"],value:string,normalizedValue:string,sourceId:string):Fact{return{id,caseId:"case-1",factType:type,value,normalizedValue,text:value,sourceText:value,sourceType:"uploaded_file",sourceId,confidence:.9,createdBy:"system",extractionMethod:"parser",createdAt:"2026-08-22T00:00:00Z"};}
describe("trust signals",()=>{it("detects conflicting dates",()=>{const conflicts=detectConflicts("case-1",[fact("a","delivery_date","Aug 07","2026-08-07","e1"),fact("b","delivery_date","Aug 09","2026-08-09","e2")]);expect(conflicts).toHaveLength(1);});it("represents missing refund information",()=>{const missing=findMissingInformation("case-1",[fact("a","delivery_date","Aug 07","2026-08-07","e1")]);expect(missing.some(item=>item.expectedFactType==="refund_date"&&item.state==="unverified")).toBe(true);});it("builds a chronological, source-linked timeline",()=>{const events=buildTimeline("case-1",[fact("b","delivery_date","Aug 07","2026-08-07","e2"),fact("a","purchase_date","Aug 03","2026-08-03","e1")]);expect(events[0]?.title).toBe("Order placed");expect(events[1]?.sourceFactId).toBe("b");});});
