import Link from "next/link";
import { sampleCases } from "@/data/demo/sample-cases";

const problemDescriptions:Record<string,string>={Documents:"Certificate information does not match supporting records.",Benefits:"An application has stopped moving and the reason is unclear.",Bills:"A bill, reading or amount does not match the evidence.",Transport:"A licence or document application is stuck in processing.",Education:"An application was rejected but the fix is unclear.",Payments:"Money moved, but the corresponding application or service did not.",Consumer:"A refund, return or service dispute has unresolved evidence."};
const steps=[["Tell us what happened","Write naturally in English, Hindi or Hinglish."],["Bring the evidence","Upload screenshots, documents, receipts, photos or messages."],["We reconstruct the case","See what is supported, what conflicts, what is missing and what happened when."],["Get the next useful step","Review the recommendation and prepare a Resolution Pack."]];
function Cta({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}){return <Link href={href} className={`inline-flex min-h-12 items-center justify-center border px-5 text-sm font-semibold transition-colors ${light?"border-white bg-white text-brand-900 hover:bg-canvas":"border-brand-700 bg-brand-700 text-white hover:bg-brand-900"}`}>{children}<span aria-hidden="true" className="ml-3">→</span></Link>}

export default function LandingPage(){return <div className="bg-canvas text-ink">
  <header className="sticky top-0 z-40 border-b border-line bg-canvas/95 backdrop-blur-sm"><div className="mx-auto flex min-h-16 max-w-7xl items-center justify-between gap-5 px-4 sm:px-6"><Link href="/" className="text-sm font-bold tracking-[.12em]">RESOLUTION ENGINE</Link><nav aria-label="Main navigation" className="hidden items-center gap-6 lg:flex"><Link href="#how" className="text-sm hover:underline">How it works</Link><Link href="#problems" className="text-sm hover:underline">Problems</Link><Link href="#why" className="text-sm hover:underline">Why Resolution Engine</Link><Link href="#samples" className="text-sm hover:underline">Sample cases</Link><Cta href="/app">Start resolving</Cta></nav><details className="relative lg:hidden"><summary className="cursor-pointer list-none border border-line px-4 py-2 text-sm font-semibold">Menu</summary><nav aria-label="Mobile navigation" className="absolute right-0 top-12 w-64 border border-line bg-paper p-3 shadow-lg"><Link href="#how" className="block min-h-11 px-3 py-3">How it works</Link><Link href="#problems" className="block min-h-11 px-3 py-3">Problems</Link><Link href="#why" className="block min-h-11 px-3 py-3">Why Resolution Engine</Link><Link href="#samples" className="block min-h-11 px-3 py-3">Sample cases</Link><Link href="/app" className="mt-2 block min-h-11 bg-brand-700 px-3 py-3 text-center font-semibold text-white">Start resolving</Link></nav></details></div></header>
  <main>
    <section className="border-b border-line"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[1.1fr_.9fr] lg:py-28"><div><p className="editorial-label text-brand-600">Resolution Engine</p><h1 className="editorial-heading mt-5 max-w-4xl text-5xl sm:text-7xl lg:text-[5.5rem]">Different problems.<br/>One Resolution Engine.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-muted">Documents, applications, bills, payments and everyday disputes become difficult when the evidence is scattered. Resolution Engine turns that mess into a case you can actually use.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Cta href="/app">Start resolving</Cta><Cta href="#samples" light>Explore sample cases</Cta></div><p className="mt-5 text-xs leading-5 text-muted">Nothing is sent or submitted without you.</p></div><div className="self-end border border-line bg-paper"><div className="p-5 sm:p-7"><p className="editorial-label text-muted">The mess</p><div className="mt-5 grid gap-px bg-line sm:grid-cols-2">{["Invoice.pdf","Status screenshot","Payment receipt","Support message","Certificate"].map(item=><span key={item} className="bg-paper px-3 py-3 text-sm">{item}</span>)}</div></div><div className="border-y border-line bg-brand-900 px-5 py-4 text-center text-xs font-bold tracking-[.16em] text-white">↓ RESOLUTION ENGINE ↓</div><div className="grid grid-cols-2 gap-px bg-line sm:grid-cols-3">{[["08","Supported facts"],["01","Conflict"],["02","Missing details"],["01","Timeline"],["01","Next step"]].map(([count,label])=><div key={label} className="bg-paper p-4"><b className="block text-2xl">{count}</b><span className="text-xs text-muted">{label}</span></div>)}</div></div></div></section>

    <section id="problems" className="scroll-mt-20 border-b border-line"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><p className="editorial-label text-brand-600">01 / Problems</p><h2 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">One engine for different kinds of problems.</h2><div className="mt-10 border-t border-line">{sampleCases.map((sample,index)=><Link key={sample.id} href={`/app?sample=${sample.id}`} className="grid gap-3 border-b border-line py-5 hover:bg-paper sm:grid-cols-[5rem_10rem_1fr_auto] sm:items-center sm:px-3"><span className="text-3xl font-semibold text-brand-600">{String(index+1).padStart(2,"0")}</span><span className="editorial-label">{sample.category}</span><span className="text-sm leading-6 text-muted">{problemDescriptions[sample.category]}</span><span className="text-sm font-semibold">Open sample →</span></Link>)}</div></div></section>

    <section id="how" className="scroll-mt-20 bg-paper"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><p className="editorial-label text-brand-600">02 / How it works</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">The case comes before the answer.</h2><div className="mt-10 grid gap-px bg-line md:grid-cols-2 xl:grid-cols-4">{steps.map(([title,copy],index)=><article key={title} className="bg-paper p-6"><span className="text-3xl font-semibold text-brand-600">{String(index+1).padStart(2,"0")}</span><h3 className="mt-7 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{copy}</p></article>)}</div></div></section>

    <section className="border-y border-line"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><p className="editorial-label text-brand-600">03 / Transformation</p><h2 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">From scattered evidence to a usable case.</h2><div className="mt-10 grid border border-line lg:grid-cols-[1fr_auto_1fr]"><div className="bg-paper p-6 sm:p-8"><p className="editorial-label text-muted">What the user has</p><ul className="mt-5 space-y-3 text-sm">{["5 screenshots","2 receipts","1 PDF","3 messages","Dates remembered roughly"].map(item=><li key={item} className="border-b border-line pb-3">{item}</li>)}</ul></div><div className="grid min-h-24 place-items-center bg-brand-900 px-8 text-center text-xs font-bold tracking-[.16em] text-white">RESOLUTION<br/>ENGINE</div><div className="bg-paper p-6 sm:p-8"><p className="editorial-label text-muted">What the user gets</p><ul className="mt-5 grid gap-3 text-sm sm:grid-cols-2">{["Supported facts","Evidence links","Conflict detection","Missing information","Case timeline","Recommended next step","Resolution Pack"].map(item=><li key={item} className="border-b border-line pb-3">{item}</li>)}</ul></div></div></div></section>

    <section id="why" className="scroll-mt-20 bg-brand-900 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="editorial-label text-brand-100">04 / How we know</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Not just an answer.<br/>A case you can inspect.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-brand-100">Important claims stay connected to their evidence. Missing or conflicting information remains visible.</p></div><div className="border border-brand-500">{[["RETURN COMPLETED","pickup-confirmation","Supported"],["REFUND DISCUSSED","support-message","Supported"],["REFUND COMPLETED","No confirming source","Not confirmed"]].map(([claim,source,status])=><div key={claim} className="grid gap-2 border-b border-brand-500 p-5 last:border-0 sm:grid-cols-[1fr_1fr_auto]"><b>{claim}</b><span className="text-sm text-brand-100">{source}</span><span className="text-xs font-bold uppercase tracking-wider">{status}</span></div>)}<div className="bg-white p-5 text-brand-900"><p className="editorial-label">Therefore</p><p className="mt-2 text-xl font-semibold">Confirm the refund status before escalating.</p></div></div></div></section>

    <section className="border-b border-line"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-2"><div><p className="editorial-label text-brand-600">05 / India-first</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Built for how problems actually arrive.</h2><p className="mt-5 text-lg leading-8 text-muted">A citizen rarely begins with a perfect form. They begin with a screenshot, an application number, a PDF, a receipt, a message or a story of what happened.</p></div><div className="border-t border-line">{["Payment ho gaya but application nahi bana.","Certificate mein naam galat hai.","Verification complete hai but status pending hai.","Bill suddenly ₹8,730 ka aa gaya.","Scholarship reject hui but reason clear nahi hai."].map(text=><p key={text} className="border-b border-line py-4 text-lg">“{text}”</p>)}<p className="mt-5 font-semibold">Resolution Engine starts there.</p></div></div></section>

    <section id="samples" className="scroll-mt-20 bg-paper"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><p className="editorial-label text-brand-600">06 / Sample cases</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">See Resolution Engine in action.</h2><div className="mt-10 grid gap-px bg-line sm:grid-cols-2 lg:grid-cols-3">{sampleCases.map(sample=><article key={sample.id} className="bg-paper p-6"><div className="flex justify-between gap-4"><p className="editorial-label text-brand-600">{sample.category}</p><span className="text-[.68rem] font-bold uppercase tracking-wider text-muted">Fictional sample</span></div><h3 className="mt-4 text-xl font-semibold">{sample.title}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-muted">{sample.summary}</p><div className="mt-5 border-y border-line py-3 text-xs text-muted"><span>{sample.source.evidence.length} Evidence</span><span className="ml-4">{sample.source.conflicts.length} Conflict</span><span className="ml-4">{sample.source.missingInformation.length} Missing</span></div><Link href={`/app?sample=${sample.id}`} className="mt-5 inline-flex min-h-11 items-center font-semibold underline underline-offset-4">Explore case →</Link></article>)}</div></div></section>

    <section className="border-y border-line"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><p className="editorial-label text-brand-600">07 / Trust</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">You stay in control.</h2><div className="mt-10 grid gap-px bg-line sm:grid-cols-2 lg:grid-cols-4">{[["Evidence-linked","Important facts stay connected to their source."],["Uncertainty visible","Missing or unclear details remain visible."],["Human review","You review meaningful actions before using them."],["No automatic submission","Nothing is sent or filed without you."]].map(([title,copy])=><article key={title} className="bg-canvas p-6"><h3 className="font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{copy}</p></article>)}</div><p className="mt-6 max-w-3xl text-xs leading-6 text-muted">Resolution Engine is an independent prototype. It is not a government portal and does not replace official authorities or professional legal advice.</p></div></section>

    <section className="bg-paper"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[.8fr_1.2fr]"><div><p className="editorial-label text-brand-600">08 / Resolution Pack</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">Leave with something useful.</h2><p className="mt-5 text-sm leading-7 text-muted">Instead of ending with a chat answer, Resolution Engine prepares a structured record you can review and use for the next step.</p><div className="mt-7"><Cta href="/app">Build my case</Cta></div></div><div className="border border-line bg-canvas p-6 sm:p-8"><p className="editorial-label">Resolution Pack / Case RE-2048</p><ol className="mt-6">{["Issue","Supported facts","Timeline","Evidence index","What remains unclear","Recommended next action","Prepared communication"].map((item,index)=><li key={item} className="grid grid-cols-[3rem_1fr] border-t border-line py-3 text-sm"><span className="text-muted">{String(index+1).padStart(2,"0")}</span><b>{item}</b></li>)}</ol></div></div></section>

    <section className="bg-brand-900 text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><p className="editorial-label text-brand-100">Ready when you are</p><h2 className="mt-3 max-w-3xl text-4xl font-semibold tracking-tight sm:text-6xl">You already have the evidence.<br/>Let’s turn it into a case.</h2><div className="mt-8"><Cta href="/app" light>Start resolving</Cta></div><p className="mt-5 text-xs text-brand-100">No automatic submissions. You review every meaningful action.</p></div></section>
  </main>
  <footer className="border-t border-line bg-canvas"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-8 text-xs text-muted sm:flex-row sm:items-center sm:justify-between sm:px-6"><b className="text-ink">RESOLUTION ENGINE</b><span>Independent hackathon prototype</span><span>Not affiliated with or endorsed by any government authority.</span></div></footer>
</div>}

