"use client";

import { useState } from "react";
import { CheckCircle2, ChevronDown, CircleHelp, LoaderCircle, ShieldCheck, ThumbsDown } from "lucide-react";
import type { Evidence } from "@/types/case";
import type { ResolutionRecommendation } from "@/types/resolution";
import { ActionPackageSection } from "@/components/action-package/action-package-section";
import { Alert } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";

function confidenceCopy(confidence:ResolutionRecommendation["confidence"]){if(confidence==="high")return "Strong evidence supports this next step.";if(confidence==="medium")return "This is useful, but some details are still uncertain.";return "More information or confirmation would make this next step stronger.";}
export function RecommendationSection({caseId,evidence,initialRecommendation,onInspectEvidence=(evidenceId)=>window.dispatchEvent(new CustomEvent("resolution:inspect-evidence",{detail:{evidenceId}}))}:{caseId:string;evidence:Evidence[];initialRecommendation?:ResolutionRecommendation;onInspectEvidence?:(evidenceId:string)=>void}){
  const [recommendation,setRecommendation]=useState(initialRecommendation);const [loading,setLoading]=useState(false);const [error,setError]=useState<string>();
  async function generate(){setLoading(true);setError(undefined);try{const response=await fetch(`/api/cases/${caseId}/recommendation`,{method:"POST"});const data=await response.json() as {recommendation?:ResolutionRecommendation;error?:string};if(!response.ok||!data.recommendation)throw new Error(data.error??"We couldn't prepare a recommendation.");setRecommendation(data.recommendation);}catch(problem){setError(problem instanceof Error?problem.message:"We couldn't prepare a recommendation.");}finally{setLoading(false);}}
  async function review(status:"approved"|"rejected"|"needs_more_information"){if(!recommendation)return;setLoading(true);setError(undefined);try{const response=await fetch(`/api/cases/${caseId}/recommendation`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const data=await response.json() as {recommendation?:ResolutionRecommendation;error?:string};if(!response.ok||!data.recommendation)throw new Error(data.error??"We couldn't save your choice.");setRecommendation(data.recommendation);}catch(problem){setError(problem instanceof Error?problem.message:"We couldn't save your choice.");}finally{setLoading(false);}}
  if(!recommendation)return <Card className="mt-6"><CardHeader><p className="text-xs font-bold uppercase tracking-[.16em] text-brand-600">Your next step</p><h2 className="mt-1 text-xl font-semibold text-ink">What should I do next?</h2></CardHeader><CardContent><p className="max-w-2xl text-sm leading-6 text-muted">We’ll use what is already in your case to suggest a safe, practical next step. Nothing will be sent or changed outside this case.</p>{error&&<div className="mt-4"><Alert tone="error">{error}</Alert></div>}<div className="mt-5"><Button onClick={generate} disabled={loading}>{loading?<><LoaderCircle size={16} className="animate-spin" aria-hidden="true"/>Preparing your next step…</>:<>Show my next step <ChevronDown size={16} aria-hidden="true"/></>}</Button></div></CardContent></Card>;
  const evidenceById=new Map(evidence.map(item=>[item.id,item]));
  return <><Card className="mt-6 overflow-hidden"><div className="bg-brand-700 px-5 py-6 text-white sm:px-6"><p className="text-xs font-bold uppercase tracking-[.16em] text-brand-100">Recommended next step</p><h2 className="mt-2 text-2xl font-semibold">{recommendation.action}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-brand-100">{recommendation.explanation}</p></div><CardContent className="space-y-5"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-brand-50 px-3 py-1 text-xs font-semibold capitalize text-brand-700">{recommendation.priority} priority</span><span className="rounded-full bg-canvas px-3 py-1 text-xs font-semibold capitalize text-ink">{recommendation.confidence} confidence</span><span className="rounded-full bg-canvas px-3 py-1 text-xs text-muted">Your approval is required</span></div>
    <section><h3 className="font-semibold text-ink">Why this is suggested</h3><ul className="mt-3 space-y-2">{recommendation.reasons.map((reason,index)=><li key={`${reason.sourceId}-${index}`} className="flex gap-2 text-sm leading-6 text-muted"><CheckCircle2 size={17} className="mt-1 shrink-0 text-brand-600" aria-hidden="true"/><span>{reason.statement}</span></li>)}</ul></section>
    {recommendation.supportingEvidence.length>0&&<section><h3 className="font-semibold text-ink">Evidence to review</h3><ul className="mt-3 space-y-2">{recommendation.supportingEvidence.map(reference=>{const item=evidenceById.get(reference.evidenceId);return <li key={reference.evidenceId}><button type="button" onClick={()=>onInspectEvidence(reference.evidenceId)} className="w-full rounded-lg border border-line bg-paper p-3 text-left text-sm hover:border-brand-500 hover:bg-brand-50" aria-label={`Inspect evidence: ${item?.filename??"evidence item"}`}><span className="font-semibold text-ink">{item?.filename??"Evidence item"}</span><span className="mt-1 block text-muted">{reference.reason}</span>{reference.sourceText&&<span className="mt-2 block text-xs leading-5 text-muted">“{reference.sourceText}”</span>}</button></li>})}</ul></section>}
    <section><h3 className="font-semibold text-ink">What is uncertain</h3>{recommendation.unresolvedQuestions.length?<ul className="mt-3 space-y-2">{recommendation.unresolvedQuestions.map(question=><li key={question} className="flex gap-2 text-sm leading-6 text-muted"><CircleHelp size={17} className="mt-1 shrink-0 text-amber-600" aria-hidden="true"/><span>{question}</span></li>)}</ul>:<p className="mt-2 text-sm text-muted">No additional uncertainty is blocking this low-risk next step.</p>}</section>
    <section className="rounded-xl bg-canvas p-4"><p className="font-semibold text-ink">What happens next</p><p className="mt-1 text-sm leading-6 text-muted">If this does not lead to a clear written response, a later stage can help review a possible escalation path. No message or complaint will be sent automatically.</p></section><details className="rounded-xl border border-line p-4"><summary className="flex cursor-pointer items-center justify-between gap-4 font-semibold text-ink">Why are you recommending this?<ChevronDown size={17} aria-hidden="true"/></summary><p className="mt-3 text-sm leading-6 text-muted">{confidenceCopy(recommendation.confidence)} This is based on case facts, timeline, unresolved questions, and synthetic demo guidance—not a legal conclusion.</p></details>{error&&<Alert tone="error">{error}</Alert>}
    <div className="flex flex-col gap-3 border-t border-line pt-5 sm:flex-row sm:flex-wrap"><Button onClick={()=>review("approved")} disabled={loading||recommendation.status==="approved"}><ShieldCheck size={17} aria-hidden="true"/>{recommendation.status==="approved"?"Recommendation selected":"Use this recommendation"}</Button><Button variant="secondary" onClick={()=>review("needs_more_information")} disabled={loading}>I need to change something</Button><Button variant="ghost" onClick={()=>review("rejected")} disabled={loading}><ThumbsDown size={16} aria-hidden="true"/>Not helpful</Button></div>{recommendation.status!=="ready_for_review"&&<p className="text-xs text-muted" role="status">Your review choice is saved. No external action was taken.</p>}</CardContent></Card>{recommendation.status==="approved"&&<ActionPackageSection caseId={caseId} evidence={evidence} onInspectEvidence={onInspectEvidence}/>}</>;
}
